print("Введите X ")
x = int(input())
print("Введите Y ")
y = int(input())
if (x>0) and (y>0) : print("Это I четверть ")
if (x>0) and (y<0) : print("Это IV четверть ") 
if (x<0) and (y>0) : print("Это II четверть ")
if (x<0) and (y<0) : print("Это III четверть ")
if (x==0) and (y>0) : print("Вы на положительной части оси Y ")
if (x==0) and (y<0) : print("Вы на отрицательной части оси Y ")
if (x>0) and (y==0) : print("Вы на положительной части оси X ")
if (x<0) and (y==0) : print("Вы на отрицательной части оси X ")
if (x==0) and (y==0) : print("Вы в НУЛЕ! ")

input()